FROM node:20-slim

WORKDIR /app

# install npm dependencies
COPY frontend/package*.json ./
RUN npm install

# app files
COPY frontend/ .

# react server
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]